'use server';
/**
 * @fileOverview A flow to retrieve a list of stocks for the trade log form.
 *
 * - listStocks - A function that returns a list of stocks.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { StockSchema, type Stock } from '@/lib/types';


export async function listStocks(): Promise<Stock[]> {
  return listStocksFlow();
}

const listStocksFlow = ai.defineFlow(
  {
    name: 'listStocksFlow',
    inputSchema: z.void(),
    outputSchema: z.array(StockSchema),
  },
  async () => {
    // In a real application, you would fetch this from a third-party API like Akshare, Alpha Vantage, or Finnhub.
    // This requires setting up an API key securely on the backend and handling the data fetching logic here.
    // For now, we return a comprehensive static list as a placeholder.
    return [
        // US Stocks (Top ~100 by Market Cap)
        { value: 'AAPL', label: '苹果 (AAPL)' },
        { value: 'MSFT', label: '微软 (MSFT)' },
        { value: 'GOOGL', label: '谷歌 (GOOGL)' },
        { value: 'GOOG', label: '谷歌 (GOOG)' },
        { value: 'AMZN', label: '亚马逊 (AMZN)' },
        { value: 'NVDA', label: '英伟达 (NVDA)' },
        { value: 'META', label: 'Meta Platforms (META)' },
        { value: 'TSLA', label: '特斯拉 (TSLA)' },
        { value: 'BRK-B', label: '伯克希尔哈撒韦 (BRK-B)' },
        { value: 'LLY', label: '礼来 (LLY)' },
        { value: 'AVGO', label: '博通 (AVGO)' },
        { value: 'JPM', label: '摩根大通 (JPM)' },
        { value: 'V', label: 'Visa (V)' },
        { value: 'XOM', label: '埃克森美孚 (XOM)' },
        { value: 'UNH', label: '联合健康 (UNH)' },
        { value: 'WMT', label: '沃尔玛 (WMT)' },
        { value: 'MA', label: '万事达 (MA)' },
        { value: 'JNJ', label: '强生 (JNJ)' },
        { value: 'PG', label: '宝洁 (PG)' },
        { value: 'HD', label: '家得宝 (HD)' },
        { value: 'COST', label: '好市多 (COST)' },
        { value: 'MRK', label: '默克 (MRK)' },
        { value: 'ABBV', label: '艾伯维 (ABBV)' },
        { value: 'CRM', label: '赛富时 (CRM)' },
        { value: 'CVX', label: '雪佛龙 (CVX)' },
        { value: 'NFLX', label: '奈飞 (NFLX)' },
        { value: 'AMD', label: '超威半导体 (AMD)' },
        { value: 'BAC', label: '美国银行 (BAC)' },
        { value: 'KO', label: '可口可乐 (KO)' },
        { value: 'PEP', label: '百事 (PEP)' },
        { value: 'ADBE', label: 'Adobe (ADBE)' },
        { value: 'TMO', label: '赛默飞世尔 (TMO)' },
        { value: 'WFC', label: '富国银行 (WFC)' },
        { value: 'CSCO', label: '思科 (CSCO)' },
        { value: 'MCD', label: '麦当劳 (MCD)' },
        { value: 'DIS', label: '迪士尼 (DIS)' },
        { value: 'ACN', label: '埃森哲 (ACN)' },
        { value: 'QCOM', label: '高通 (QCOM)' },
        { value: 'GE', label: '通用电气 (GE)' },
        { value: 'LIN', label: '林德 (LIN)' },
        { value: 'VZ', label: '威瑞森 (VZ)' },
        { value: 'INTC', label: '英特尔 (INTC)' },
        { value: 'UBER', label: '优步 (UBER)' },
        { value: 'INTU', label: '财捷 (INTU)' },
        { value: 'IBM', label: 'IBM (IBM)' },
        { value: 'CAT', label: '卡特彼勒 (CAT)' },
        { value: 'AMAT', label: '应用材料 (AMAT)' },
        { value: 'PFE', label: '辉瑞 (PFE)' },
        { value: 'NOW', label: 'ServiceNow (NOW)' },
        { value: 'CMG', label: '奇波雷墨西哥烧烤 (CMG)' },
        { value: 'T', label: 'AT&T (T)' },
        { value: 'UNP', label: '联合太平洋 (UNP)' },
        { value: 'AXP', label: '美国运通 (AXP)' },
        { value: 'TXN', label: '德州仪器 (TXN)' },
        { value: 'SPGI', label: '标普全球 (SPGI)' },
        { value: 'GS', label: '高盛 (GS)' },
        { value: 'MS', label: '摩根士丹利 (MS)' },
        { value: 'BLK', label: '贝莱德 (BLK)' },
        { value: 'BA', label: '波音 (BA)' },
        { value: 'DE', label: '迪尔 (DE)' },
        { value: 'RTX', label: '雷神技术 (RTX)' },
        { value: 'PLD', label: '普洛斯 (PLD)' },
        { value: 'SBUX', label: '星巴克 (SBUX)' },
        { value: 'ISRG', label: '直觉外科 (ISRG)' },
        { value: 'LMT', label: '洛克希德·马丁 (LMT)' },
        { value: 'COP', label: '康菲石油 (COP)' },
        { value: 'C', label: '花旗集团 (C)' },
        { value: 'BMY', label: '百时美施贵宝 (BMY)' },
        { value: 'SCHW', label: '嘉信理财 (SCHW)' },
        { value: 'CVS', label: 'CVS健康 (CVS)' },
  
        // Hong Kong Stocks (Top ~50 by Market Cap)
        { value: '0700.HK', label: '腾讯控股 (0700.HK)' },
        { value: '9988.HK', label: '阿里巴巴-SW (9988.HK)' },
        { value: '0005.HK', label: '汇丰控股 (0005.HK)' },
        { value: '3690.HK', label: '美团-W (3690.HK)' },
        { value: '1299.HK', label: '友邦保险 (1299.HK)' },
        { value: '0941.HK', label: '中国移动 (0941.HK)' },
        { value: '0939.HK', label: '建设银行 (0939.HK)' },
        { value: '1398.HK', label: '工商银行 (1398.HK)' },
        { value: '0883.HK', label: '中国海洋石油 (0883.HK)' },
        { value: '2318.HK', label: '中国平安 (2318.HK)' },
        { value: '3988.HK', label: '中国银行 (3988.HK)' },
        { value: '1810.HK', label: '小米集团-W (1810.HK)' },
        { value: '0388.HK', label: '香港交易所 (0388.HK)' },
        { value: '9618.HK', label: '京东集团-SW (9618.HK)' },
        { value: '1211.HK', label: '比亚迪股份 (1211.HK)' },
        { value: '9999.HK', label: '网易-S (9999.HK)' },
        { value: '2628.HK', label: '中国人寿 (2628.HK)' },
        { value: '0857.HK', label: '中国石油股份 (0857.HK)' },
        { value: '0688.HK', label: '中国海外发展 (0688.HK)' },
        { value: '1088.HK', label: '中国神华 (1088.HK)' },
        { value: '1024.HK', label: '快手-W (1024.HK)' },
        { value: '0001.HK', label: '长和 (0001.HK)' },
        { value: '0016.HK', label: '新鸿基地产 (0016.HK)' },
        { value: '2020.HK', label: '安踏体育 (2020.HK)' },
        { value: '0241.HK', label: '阿里健康 (0241.HK)' },
        { value: '1044.HK', label: '恒安国际 (1044.HK)' },
        { value: '0002.HK', label: '中电控股 (0002.HK)' },
        { value: '0003.HK', label: '香港中华煤气 (0003.HK)' },
        { value: '1109.HK', label: '华润置地 (1109.HK)' },
        { value: '2331.HK', label: '李宁 (2331.HK)' },
        { value: '0175.HK', label: '吉利汽车 (0175.HK)' },
        { value: '3968.HK', label: '招商银行 (3968.HK)' },
        { value: '6690.HK', label: '海尔智家 (6690.HK)' },
        { value: '0960.HK', label: '龙湖集团 (0960.HK)' },
        { value: '0027.HK', label: '银河娱乐 (0027.HK)' },
        { value: '1928.HK', label: '金沙中国有限公司 (1928.HK)' },
  
        // A-shares Stocks (Shanghai & Shenzhen, Top ~100 by Market Cap)
        { value: '600519.SS', label: '贵州茅台 (600519.SS)' },
        { value: '601398.SS', label: '工商银行 (601398.SS)' },
        { value: '601288.SS', label: '农业银行 (601288.SS)' },
        { value: '601857.SS', label: '中国石油 (601857.SS)' },
        { value: '601988.SS', label: '中国银行 (601988.SS)' },
        { value: '601318.SS', label: '中国平安 (601318.SS)' },
        { value: '600036.SS', label: '招商银行 (600036.SS)' },
        { value: '300750.SZ', label: '宁德时代 (300750.SZ)' },
        { value: '601628.SS', label: '中国人寿 (601628.SS)' },
        { value: '601088.SS', label: '中国神华 (601088.SS)' },
        { value: '000858.SZ', label: '五粮液 (000858.SZ)' },
        { value: '600028.SS', label: '中国石化 (600028.SS)' },
        { value: '002594.SZ', label: '比亚迪 (002594.SZ)' },
        { value: '000001.SZ', label: '平安银行 (000001.SZ)' },
        { value: '601166.SS', label: '兴业银行 (601166.SS)' },
        { value: '000333.SZ', label: '美的集团 (000333.SZ)' },
        { value: '600276.SS', label: '恒瑞医药 (600276.SS)' },
        { value: '600887.SS', label: '伊利股份 (600887.SS)' },
        { value: '600309.SS', label: '万华化学 (600309.SS)' },
        { value: '601899.SS', label: '紫金矿业 (601899.SS)' },
        { value: '002475.SZ', label: '立讯精密 (002475.SZ)' },
        { value: '601668.SS', label: '中国建筑 (601668.SS)' },
        { value: '600000.SS', label: '浦发银行 (600000.SS)' },
        { value: '300760.SZ', label: '迈瑞医疗 (300760.SZ)' },
        { value: '002714.SZ', label: '牧原股份 (002714.SZ)' },
        { value: '000651.SZ', label: '格力电器 (000651.SZ)' },
        { value: '601998.SS', label: '中信银行 (601998.SS)' },
        { value: '600030.SS', label: '中信证券 (600030.SS)' },
        { value: '300059.SZ', label: '东方财富 (300059.SZ)' },
        { value: '600585.SS', label: '海螺水泥 (600585.SS)' },
        { value: '002142.SZ', label: '宁波银行 (002142.SZ)' },
        { value: '601328.SS', label: '交通银行 (601328.SS)' },
        { value: '000002.SZ', label: '万科A (000002.SZ)' },
        { value: '601211.SS', 'label': '国泰君安 (601211.SS)' },
        { value: '600048.SS', label: '保利发展 (600048.SS)' },
        { value: '000725.SZ', label: '京东方A (000725.SZ)' },
        { value: '600436.SS', label: '片仔癀 (600436.SS)' },
        { value: '300124.SZ', label: '汇川技术 (300124.SZ)' },
        { value: '002352.SZ', label: '顺丰控股 (002352.SZ)' },
        { value: '601006.SS', label: '大秦铁路 (601006.SS)' },
        { value: '002415.SZ', label: '海康威视 (002415.SZ)' },
        { value: '601766.SS', label: '中国中车 (601766.SS)' },
        { value: '601818.SS', label: '光大银行 (601818.SS)' },
        { value: '300308.SZ', label: '中际旭创 (300308.SZ)' },
        { value: '600809.SS', label: '山西汾酒 (600809.SS)' },
        { value: '000568.SZ', label: '泸州老窖 (000568.SZ)' },
        { value: '600019.SS', label: '宝钢股份 (600019.SS)' },
        { value: '603288.SS', label: '海天味业 (603288.SS)' },
        { value: '603508.SS', label: '韦尔股份 (603508.SS)' },
        { value: '000063.SZ', label: '中兴通讯 (000063.SZ)' },
      ];
  }
);
