import type { Config } from "tailwindcss"
import defaultTheme from "tailwindcss/defaultTheme"

const config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", ...defaultTheme.fontFamily.sans],
        body: ["Inter", "sans-serif"],
        headline: ["Space Grotesk", "sans-serif"],
        mono: ["Berkeley Mono", "ui-monospace", "SF Mono", "Menlo", "monospace"],
        code: ["monospace"],
      },
      colors: {
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        "on-primary": "hsl(var(--primary-foreground))",
        "primary-container": "hsl(var(--primary-container))",
        "on-primary-container": "hsl(var(--on-primary-container))",
        secondary: "hsl(var(--secondary))",
        "on-secondary": "hsl(var(--secondary-foreground))",
        "secondary-container": "hsl(var(--secondary-container))",
        "on-secondary-container": "hsl(var(--on-secondary-container))",
        tertiary: "hsl(var(--tertiary))",
        "on-tertiary": "hsl(var(--tertiary-foreground))",
        "tertiary-container": "hsl(var(--tertiary-container))",
        "on-tertiary-container": "hsl(var(--on-tertiary-container))",
        error: "hsl(var(--destructive))",
        "on-error": "hsl(var(--destructive-foreground))",
        "error-container": "hsl(var(--destructive-container))",
        "on-error-container": "hsl(var(--on-destructive-container))",
        background: "hsl(var(--background))",
        "on-background": "hsl(var(--foreground))",
        surface: "hsl(var(--surface))",
        "on-surface": "hsl(var(--foreground))",
        "surface-variant": "hsl(var(--surface-variant))",
        "on-surface-variant": "hsl(var(--on-surface-variant))",
        outline: "hsl(var(--border))",
        "inverse-on-surface": "hsl(var(--inverse-on-surface))",
        "inverse-surface": "hsl(var(--inverse-surface))",
        "inverse-primary": "hsl(var(--inverse-primary))",
        shadow: "hsl(var(--shadow))",
        "surface-tint": "hsl(var(--primary))",
        "outline-variant": "hsl(var(--outline-variant))",
        scrim: "hsl(var(--scrim))",
        "surface-container-highest": "hsl(var(--surface-container-highest))",
        "surface-container-high": "hsl(var(--surface-container-high))",
        "surface-container": "hsl(var(--surface-container))",
        "surface-container-low": "hsl(var(--surface-container-low))",
        "surface-container-lowest": "hsl(var(--surface-container-lowest))",
        "surface-bright": "hsl(var(--surface-bright))",
        "surface-dim": "hsl(var(--surface-dim))",

        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        /* ── Pinterest design system static tokens ── */
        pt: {
          bg:             '#ffffff',
          fog:            '#f6f6f3',
          sand:           '#e5e5e0',
          warm:           '#e0e0d9',
          heading:        '#211922',
          body:           '#62625b',
          muted:          '#91918c',
          border:         '#e5e5e0',
          'border-hover': '#bcbcb3',
          red:            '#e60023',
          'red-h':        '#ad081b',
          'red-l':        'rgba(230,0,35,0.08)',
          dark:           '#33332e',
          focus:          '#435ee5',
        },
        /* ── Stripe design system static tokens ── */
        st: {
          bg:           '#ffffff',
          surface:      '#f8f9fb',
          heading:      '#061b31',
          label:        '#273951',
          body:         '#64748d',
          border:       '#e5edf5',
          purple:       '#533afd',
          'purple-h':   '#4434d4',
          'purple-l':   '#b9b9f9',
          dark:         '#1c1e54',
          success:      '#15be53',
          'success-t':  '#108c3d',
        },
        /* ── Linear design system static tokens ── */
        ln: {
          bg:           '#08090a',
          panel:        '#0f1011',
          card:         '#191a1b',
          hover:        '#28282c',
          text:         '#f7f8f8',
          'text-2':     '#d0d6e0',
          'text-3':     '#8a8f98',
          'text-4':     '#62666d',
          indigo:       '#5e6ad2',
          violet:       '#7170ff',
          'violet-h':   '#828fff',
          'border-s':   'rgba(255,255,255,0.08)',   // border standard
          'border-sub': 'rgba(255,255,255,0.05)',   // border subtle
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        "extra-small": "4px",
        small: "8px",
        medium: "12px",
        large: "16px",
        "extra-large": "28px",
        full: "9999px",
      },
      fontSize: {
        "display-large": ["57px", { lineHeight: "64px", fontWeight: "400" }],
        "display-medium": ["45px", { lineHeight: "52px", fontWeight: "400" }],
        "display-small": ["36px", { lineHeight: "44px", fontWeight: "400" }],
        "headline-large": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "headline-medium": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "headline-small": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "title-large": ["22px", { lineHeight: "28px", fontWeight: "400" }],
        "title-medium": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "title-small": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-large": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-medium": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-small": ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "body-large": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-medium": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-small": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      boxShadow: {
        "level-1": "0px 1px 3px 1px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.30)",
        "level-2": "0px 2px 6px 2px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.30)",
        "level-3": "0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)",
        "level-4": "0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)",
        "level-5": "0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)",
        "soft-card": "0 2px 4px 0px #E0E0E0",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        ripple: 'ripple 0.4s ease-out',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config

